# 1. Análisis exploratorio de Datos Calidad

In [2]:
import pandas as pd

In [5]:
ic_ips=pd.read_csv("C:/Users/DARLAN/Documents/GitHub/Proyecto_DSA/data/raw/Indicadores_salud/Clicsalud-_Indicadores_de_calidad_IPS_20251018.csv", encoding="utf-8")

In [6]:
ic_ips.head()

,coddepartamento,departamento,codmunicipio,municipio,idips,ips,nomcategorias,nomservicio,nomespecifique,nomindicador,numerador,denominador,resultado,nomunidad,nomfuente,enlace,periodo
0,-1,1,0,Total,Total,VIDA SANA IPS LTDA,EFECTIVIDAD,URGENCIAS,ATENCION MATERNA,Proporción de partos por cesárea,891,"3,363",26.49,PORCENTAJE,MinSalud,http://rssvr2.sispro.gov.co/IndicadoresMOCA/,201606
1,-1,1,0,Total,Total,VIDA SANA IPS LTDA,EFECTIVIDAD,URGENCIAS,ATENCION MATERNA,Proporción de partos por cesárea,774,"2,855",27.11,PORCENTAJE,MinSalud,http://rssvr2.sispro.gov.co/IndicadoresMOCA/,201612
2,-1,1,0,Total,Total,VIDA SANA IPS LTDA,EFECTIVIDAD,URGENCIAS,ATENCION MATERNA,Proporción de partos por cesárea,814,"2,912",27.95,PORCENTAJE,MinSalud,http://rssvr2.sispro.gov.co/IndicadoresMOCA/,201706
3,-1,1,0,Total,Total,VIDA SANA IPS LTDA,EFECTIVIDAD,URGENCIAS,ATENCION MATERNA,Proporción de partos por cesárea,"1,025","3,007",34.09,PORCENTAJE,MinSalud,http://rssvr2.sispro.gov.co/IndicadoresMOCA/,201712
4,-1,1,0,Total,Total,VIDA SANA IPS LTDA,EFECTIVIDAD,URGENCIAS,ATENCION MATERNA,Proporción de partos por cesárea,683,"2,705",25.25,PORCENTAJE,MinSalud,http://rssvr2.sispro.gov.co/IndicadoresMOCA/,201806

encontramos que hay departamentos con cod departamento -1, hacemos la respectiva limpieza para evitar problemas

In [10]:
ic_ips=ic_ips[ic_ips["coddepartamento"]!=-1]
ic_ips.head()

,coddepartamento,departamento,codmunicipio,municipio,idips,ips,nomcategorias,nomservicio,nomespecifique,nomindicador,numerador,denominador,resultado,nomunidad,nomfuente,enlace,periodo
22,11,"Bogotá, D.C.",0,Total,Total,VIDA SANA IPS LTDA,EFECTIVIDAD,HOSPITALARIA,PEDIATRIA,Proporción de reingreso hospitalario por Inf...,393,"8,828",4.45,PORCENTAJE,MinSalud,http://rssvr2.sispro.gov.co/IndicadoresMOCA/,201606
23,11,"Bogotá, D.C.",0,Total,Total,VIDA SANA IPS LTDA,EFECTIVIDAD,HOSPITALARIA,PEDIATRIA,Proporción de reingreso hospitalario por Inf...,235,"5,985",3.93,PORCENTAJE,MinSalud,http://rssvr2.sispro.gov.co/IndicadoresMOCA/,201612
24,11,"Bogotá, D.C.",0,Total,Total,VIDA SANA IPS LTDA,EFECTIVIDAD,HOSPITALARIA,PEDIATRIA,Proporción de reingreso hospitalario por Inf...,304,"8,997",3.38,PORCENTAJE,MinSalud,http://rssvr2.sispro.gov.co/IndicadoresMOCA/,201706
25,11,"Bogotá, D.C.",0,Total,Total,VIDA SANA IPS LTDA,EFECTIVIDAD,HOSPITALARIA,PEDIATRIA,Proporción de reingreso hospitalario por Inf...,344,"8,598",4,PORCENTAJE,MinSalud,http://rssvr2.sispro.gov.co/IndicadoresMOCA/,201712
26,11,"Bogotá, D.C.",0,Total,Total,VIDA SANA IPS LTDA,EFECTIVIDAD,HOSPITALARIA,PEDIATRIA,Proporción de reingreso hospitalario por Inf...,755,"14,831",5.09,PORCENTAJE,MinSalud,http://rssvr2.sispro.gov.co/IndicadoresMOCA/,201806

separamos el año y el mes de la medición

In [13]:
ic_ips["periodo"]=ic_ips["periodo"].astype(str)
ic_ips["anio"]=ic_ips["periodo"].str[:4]
ic_ips["mes"]=ic_ips["periodo"].str[4:]

In [14]:
print(ic_ips[["periodo", "anio", "mes"]].head())

   periodo  anio mes
22  201606  2016  06
23  201612  2016  12
24  201706  2017  06
25  201712  2017  12
26  201806  2018  06

In [ ]:
import pandas as pd


cols = ["numerador", "denominador", "resultado"]
for c in cols:
    ic_ips[c] = (
        ic_ips[c]
        .astype(str)          
        .str.replace(",", "", regex=False)  
        .astype(float)         
    )

# Estadísticas descriptivas básicas
estadisticas = ic_ips[cols].describe().T  
print(estadisticas)


promedios = ic_ips[cols].mean()
medianas = ic_ips[cols].median()
desviaciones = ic_ips[cols].std()

print("\nPromedios:\n", promedios)
print("\nMedianas:\n", medianas)
print("\nDesviaciones estándar:\n", desviaciones)

                count          mean           std  min        25%     50%  \
numerador    301218.0  27815.780797  1.396131e+06  0.0   3.000000  115.00
denominador  301218.0   3586.149095  9.431938e+04  0.0  34.000000  166.00
resultado    301218.0     66.786465  2.141229e+03  0.0   0.699625   86.32

               75%          max
numerador    617.0  410811057.0
denominador  689.0   15007400.0
resultado    100.0     830880.0

Promedios:
 numerador      27815.780797
denominador     3586.149095
resultado         66.786465
dtype: float64

Medianas:
 numerador      115.00
denominador    166.00
resultado       86.32
dtype: float64

Desviaciones estándar:
 numerador      1.396131e+06
denominador    9.431938e+04
resultado      2.141229e+03
dtype: float64

se encontraron elementos interesantes, donde el denominador tiene una alta variabilidad, en comparación el numerador, lo que desde la intuición nos podría indicar que hay un desempeño bueno de las IPS en la gestión de servicios de salud, lo cual nos puede resultar de útilidad a la hora de evidenciar cambios en las métricas de bienestar o conformidad frente a la labor que desempeñan en el sistema de salud

In [16]:
ic_ips.to_csv("data/processed/ic_ips.csv", index=False)

Posterior a esto, se hace versionamiento a dvc para posterior tratamiento en el desarrollo de los ejercicios

Ahora hacemos lo mismo para estadisticas de EPS

In [17]:
ic_eps=pd.read_csv("C:/Users/DARLAN/Documents/GitHub/Proyecto_DSA/data/raw/Indicadores_salud/Clicsalud-_Indicadores_de_calidad_EPS_20251018.csv", encoding="utf-8")

In [18]:
ic_eps.head()

,codigo,ideps,eps,nomcategorias,nomservicio,nomespecifique,nomindicador,resultado,nomunidad,nomfuente,fecha_corte,linkfuente
0,E.3.1,CCF001,COMFAMILIAR CAMACOL,Tiempos de espera,Citas médicas,Mostrar resultado,Tiempo promedio de espera para la asignación d...,0,Días,MinSalud,20160630,http://rssvr2.sispro.gov.co/IndicadoresMOCA/
1,E.3.1,CCF002,CONFAMA,Tiempos de espera,Citas médicas,Mostrar resultado,Tiempo promedio de espera para la asignación d...,0,Días,MinSalud,20160630,http://rssvr2.sispro.gov.co/IndicadoresMOCA/
2,E.3.1,CCF007,COMFAMILIAR CARTAGENA,Tiempos de espera,Citas médicas,Mostrar resultado,Tiempo promedio de espera para la asignación d...,4.32,Días,MinSalud,20160630,http://rssvr2.sispro.gov.co/IndicadoresMOCA/
3,E.3.1,CCF009,COMFABOY,Tiempos de espera,Citas médicas,Mostrar resultado,Tiempo promedio de espera para la asignación d...,1,Días,MinSalud,20160630,http://rssvr2.sispro.gov.co/IndicadoresMOCA/
4,E.3.1,CCF015,COMFACOR,Tiempos de espera,Citas médicas,Mostrar resultado,Tiempo promedio de espera para la asignación d...,1.64,Días,MinSalud,20160630,http://rssvr2.sispro.gov.co/IndicadoresMOCA/

In [20]:
#separamos fecha de corte 
ic_eps["fecha_corte"]=ic_eps["fecha_corte"].astype(str)
ic_eps["anio"]=ic_eps["fecha_corte"].str[:4]
ic_eps["mes"]=ic_eps["fecha_corte"].str[4:]

Este tratamiento será particularmente útil a la hora de hacer análisis temporales del desempeño de las EPS en el tiempo, como aproximación a la calidad de su servicio

In [21]:
print(ic_eps[["fecha_corte", "anio", "mes"]].head())

  fecha_corte  anio   mes
0    20160630  2016  0630
1    20160630  2016  0630
2    20160630  2016  0630
3    20160630  2016  0630
4    20160630  2016  0630

In [22]:
cols = ["resultado"]
for c in cols:
    ic_eps[c] = (
        ic_eps[c]
        .astype(str)          
        .str.replace(",", "", regex=False)  
        .astype(float)         
    )

# Estadísticas descriptivas básicas
estadisticas = ic_eps[cols].describe().T  
print(estadisticas)


promedios = ic_eps[cols].mean()
medianas = ic_eps[cols].median()
desviaciones = ic_eps[cols].std()

print("\nPromedios:\n", promedios)
print("\nMedianas:\n", medianas)
print("\nDesviaciones estándar:\n", desviaciones)

            count      mean        std  min   25%   50%   75%     max
resultado  7785.0  3.871029  99.990271  0.0  0.16  1.36  2.87  8748.0

Promedios:
 resultado    3.871029
dtype: float64

Medianas:
 resultado    1.36
dtype: float64

Desviaciones estándar:
 resultado    99.990271
dtype: float64

hay una altísima variabilidad en el resultado, que es particularmente importante ya que es una medición de tiempos de atención, lo cual es fundamental a la hora de medir la satisfacción de las personas frente al servicio que brindan las EPS.

In [23]:
ic_eps.to_csv("data/processed/ic_eps.csv", index=False)

Hacemos versionamiento para DVC

# Giros Salud

In [1]:
import pandas as pd

In [18]:
giros=pd.read_csv("C:/Users/Asus/Documents/GitHub/Proyecto_DSA/data/raw/Giros/Recursos_del_Sistema_General_Giros_20251018.csv", sep=";", encoding="utf-8")

In [19]:
giros.head()

,Fecha de pago,Identificacion- NIT,Nombre Razon Social,Descripcion,Fuente,Valor,Concepto Pago,Ordenes de Pago
0,29/01/2015,800136069,MUNICIPIO DE FORTUL,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,27047767,GIRO SGP SALUD PUBLICA VIG 2014,9207515
1,29/01/2015,890000464,MUNICIPIO DE ARMENIA,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,130243583,GIRO SGP SALUD PUBLICA VIG 2014,9207615
2,29/01/2015,899999372,MUNICIPIO DE SIBATE,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,12600367,GIRO SGP SALUD PUBLICA VIG 2014,9207715
3,29/01/2015,890980112,MUNICIPIO DE BELLO,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,214941350,GIRO SGP SALUD PUBLICA VIG 2014,9207815
4,29/01/2015,890985285,MUNICIPIO DE VEGACHI,SISTEMA GENERAL DE PARTICIPACIONES SALUD PUBLI...,Nación,9040907,GIRO SGP SALUD PUBLICA VIG 2014,9207915

In [20]:
giros.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50065 entries, 0 to 50064
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Fecha de pago        50065 non-null  object
 1   Identificacion- NIT  50065 non-null  int64
 2   Nombre Razon Social  50065 non-null  object
 3   Descripcion          50065 non-null  object
 4   Fuente               50065 non-null  object
 5   Valor                50065 non-null  int64
 6   Concepto Pago        50065 non-null  object
 7   Ordenes de Pago      50065 non-null  object
dtypes: int64(2), object(6)
memory usage: 3.1+ MB

In [21]:


cols = ["Valor"]
for c in cols:
    giros[c] = (
        giros[c]
        .astype(str)          
        .str.replace(",", "", regex=False)  
        .astype(float)         
    )

# Estadísticas descriptivas básicas
estadisticas = giros[cols].describe().T  
print(estadisticas)


promedios = giros[cols].mean()
medianas = giros[cols].median()
desviaciones = giros[cols].std()

print("\nPromedios:\n", promedios)
print("\nMedianas:\n", medianas)
print("\nDesviaciones estándar:\n", desviaciones)

         count          mean           std      min        25%         50%  \
Valor  50065.0  8.722483e+07  3.634132e+08  19935.0  7543224.0  16194889.0

              75%           max
Valor  31524746.0  1.593938e+10

Promedios:
 Valor    8.722483e+07
dtype: float64

Medianas:
 Valor    16194889.0
dtype: float64

Desviaciones estándar:
 Valor    3.634132e+08
dtype: float64

Hay una altísima variabilidad en los giros realizados a los municipios, lo cual en principio, puede explicar dinámicas de diferenciación de servicios territoriales, y por ende, en la atención a personas en municipios. La intuición señala que debería existir una correlación entre demoras en la atención o servicio de salud en municipios con partidas presupuestales menores.

In [22]:
giros.to_csv("data/processed/giros.csv", index=False)

In [23]:
pila=pd.read_csv("C:/Users/Asus/Documents/GitHub/Proyecto_DSA/data/raw/PILA/Planilla_Integrada_de_Liquidación_de_Aportes_-_PILA_20251018.csv")

In [24]:
pila.head()

,Fecha,TipoAporteDesc,TipoCotizantePilaDesc,ActividadEconomicaDesc,RangoIBCDesc,NumeroCotizantes,NumeroCotizaciones
0,2021/01/01,A FONDO DE SOLIDARIDAD PENSIONAL A SUBCUENTA D...,DEPENDIENTE,2819 - Fabricación De Otros Tipos De Maquinari...,MENOR A 1 SMLMV,27,27
1,2021/03/01,A RIESGOS LABORALES,DEPENDIENTE,9311 - Gestión De Instalaciones Deportivas,MAYOR O IGUAL A 10 SMLMV,5,5
2,2021/05/01,A SALUD,ESTUDIANTES (RÉGIMEN ESPECIAL-LEY 789/2002),8559 - Otros Tipos De Educación N.C.P.,MENOR A 1 SMLMV,2,2
3,2021/05/01,APORTE SENA,DEPENDIENTE,3220 - Fabricación De Instrumentos Musicales,MAYOR O IGUAL A 4 SMLMV Y MENOR QUE 10 SMLMV,3,3
4,2021/06/01,A SALUD,INDEPENDIENTE,3830 - Recuperación De Materiales,MAYOR O IGUAL A 2 SMLMV Y MENOR QUE 4 SMLMV,12,12

In [25]:
pila.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276947 entries, 0 to 1276946
Data columns (total 7 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   Fecha                   1276947 non-null  object
 1   TipoAporteDesc          1276947 non-null  object
 2   TipoCotizantePilaDesc   1276947 non-null  object
 3   ActividadEconomicaDesc  1276947 non-null  object
 4   RangoIBCDesc            1276947 non-null  object
 5   NumeroCotizantes        1276947 non-null  object
 6   NumeroCotizaciones      1276947 non-null  object
dtypes: object(7)
memory usage: 68.2+ MB

In [33]:
col = ["NumeroCotizantes", "NumeroCotizaciones"]

for c in col:
    pila[c] = (pila[c]
                .astype(str)
                .str.replace('\u00a0', '', regex=False)     
                .str.replace(r'\s+', '', regex=True)        
                .str.replace(',', '', regex=False))         

pila[col] = pila[col].apply(pd.to_numeric, errors="coerce")

In [34]:
pila.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1276947 entries, 0 to 1276946
Data columns (total 7 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   Fecha                   1276947 non-null  object
 1   TipoAporteDesc          1276947 non-null  object
 2   TipoCotizantePilaDesc   1276947 non-null  object
 3   ActividadEconomicaDesc  1276947 non-null  object
 4   RangoIBCDesc            1276947 non-null  object
 5   NumeroCotizantes        1276947 non-null  int64
 6   NumeroCotizaciones      1276947 non-null  int64
dtypes: int64(2), object(5)
memory usage: 68.2+ MB

In [35]:
cols = ["NumeroCotizantes", "NumeroCotizaciones"]
for c in cols:
    pila[c] = (
        pila[c]
        .astype(str)          
        .str.replace(",", "", regex=False)  
        .astype(float)         
    )

# Estadísticas descriptivas básicas
estadisticas = pila[cols].describe().T  
print(estadisticas)


promedios = pila[cols].mean()
medianas = pila[cols].median()
desviaciones = pila[cols].std()

print("\nPromedios:\n", promedios)
print("\nMedianas:\n", medianas)
print("\nDesviaciones estándar:\n", desviaciones)

                        count        mean          std  min  25%   50%    75%  \
NumeroCotizantes    1276947.0  937.771321  8306.646465  1.0  3.0  17.0  141.0
NumeroCotizaciones  1276947.0  939.821650  8324.019291  1.0  3.0  17.0  141.0

                         max
NumeroCotizantes    650308.0
NumeroCotizaciones  651017.0

Promedios:
 NumeroCotizantes      937.771321
NumeroCotizaciones    939.821650
dtype: float64

Medianas:
 NumeroCotizantes      17.0
NumeroCotizaciones    17.0
dtype: float64

Desviaciones estándar:
 NumeroCotizantes      8306.646465
NumeroCotizaciones    8324.019291
dtype: float64

hay una baja diferenciación entre las dos variables númericas de cotizantes y número de cotizaciones, lo cual valdría la pena explorar en mayor medida, lo que nos puede generar problemas de multicolinealidad en caso de la implementación de modelos de regresión, por lo que sería necesario incluir modelos que incluyan penalización para minimizar el riesgo de generar correlaciones espurias.

In [36]:
pila.to_csv("data/processed/pila.csv")

In [37]:
#sivigila 

sivigila=pd.read_csv("C:/Users/Asus/Documents/GitHub/Proyecto_DSA/data/raw/sivigila/DA-SIVIGILA_2021_INS_20251018.csv")

In [38]:
sivigila.head()

,COD_EVE,Nombre_evento,SEMANA,ANO,Municipio_ocurrencia,Departamento_ocurrencia,conteo
0,100,ACCIDENTE OFIDICO,1,"2,021",AMALFI,ANTIOQUIA,2
1,100,ACCIDENTE OFIDICO,1,"2,021",BOSCONIA,CESAR,1
2,100,ACCIDENTE OFIDICO,1,"2,021",EL TAMBO,CAUCA,1
3,100,ACCIDENTE OFIDICO,1,"2,021",GAMARRA,CESAR,1
4,100,ACCIDENTE OFIDICO,1,"2,021",MARIA LA BAJA,BOLIVAR,2

In [39]:
col = ["ANO", "conteo"]

for c in col:
    sivigila[c] = (sivigila[c]
                .astype(str)
                .str.replace('\u00a0', '', regex=False)     
                .str.replace(r'\s+', '', regex=True)        
                .str.replace(',', '', regex=False))         

sivigila[col] = sivigila[col].apply(pd.to_numeric, errors="coerce")

In [41]:

for c in col:
    sivigila[c] = (
        sivigila[c]
        .astype(str)          
        .str.replace(",", "", regex=False)  
        .astype(float)         
    )

# Estadísticas descriptivas básicas
estadisticas = sivigila[col].describe().T  
print(estadisticas)


promedios = sivigila[col].mean()
medianas = sivigila[col].median()
desviaciones = sivigila[col].std()

print("\nPromedios:\n", promedios)
print("\nMedianas:\n", medianas)
print("\nDesviaciones estándar:\n", desviaciones)

           count         mean        std     min     25%     50%     75%  \
ANO     187598.0  2021.000000   0.000000  2021.0  2021.0  2021.0  2021.0
conteo  187598.0     3.315408  12.214147     1.0     1.0     1.0     2.0

           max
ANO     2021.0
conteo   546.0

Promedios:
 ANO       2021.000000
conteo       3.315408
dtype: float64

Medianas:
 ANO       2021.0
conteo       1.0
dtype: float64

Desviaciones estándar:
 ANO        0.000000
conteo    12.214147
dtype: float64

el conteo es una variable que es necesario indagar en mayor medida, su alta variabilidad, ya que la intuición señala que es altamente probable que exista una correlación con la población de municipio, donde se esperaría que municipios con mayor volumen de población tenga mayor presencia de ejercicios de vigilancia.

In [42]:
sivigila.to_csv("data/processed/sivigila.csv")

In [43]:
#instituciones de salud

instituciones=pd.read_csv("data/raw/instituciones/Listado_de_Instituciones_de_Salud_20251018.csv")

In [44]:
instituciones.head()

,CodigoPrestador,CodigoHabilitacionSede,ESE,NaturalezaJuridica,ClasePrestadorDesc,FechaCorte
0,9100100019,912630001911,SI,Pública,Instituciones Prestadoras de Servicios de Salu...,Fecha corte REPS: Jul 4 2023 1:19PM
1,9100100019,914050001914,SI,Pública,Instituciones Prestadoras de Servicios de Salu...,Fecha corte REPS: Jul 4 2023 1:19PM
2,9100100019,914070001915,SI,Pública,Instituciones Prestadoras de Servicios de Salu...,Fecha corte REPS: Jul 4 2023 1:19PM
3,9100100019,914300001916,SI,Pública,Instituciones Prestadoras de Servicios de Salu...,Fecha corte REPS: Jul 4 2023 1:19PM
4,9100100017,910010001701,NaN,Privada,Profesional Independiente,Fecha corte REPS: Jul 4 2023 1:19PM

no es necesario ajustar la base, se versiona para dvc

In [46]:
instituciones.to_csv("data/processed/instituciones.csv")

In [47]:
#Sisben

sisben=pd.read_csv("data/raw/sisben/DNP_-_Sisbén_Hogares_20251018.csv")

In [48]:
sisben.head()

,cod_mpio,ZONA,llave,CORTE,HOGAR,FEX,HOG001,HOG002,HOG003,HOG004,...,HOG018,HOG019,HOG020,HOG021,HOG022,HOG023,HOG024,HOG025,HOG026,HOG027
0,5001,1,1,SIV_2022,1,761.19639279,1,4,2,1,...,1,2,1,2,2,2,2,2,2,2
1,5001,2,2,SIV_2022,1,23.954887218,3,3,2,2,...,1,1,2,2,2,2,2,2,2,4
2,5001,1,3,SIV_2022,1,761.19639279,4,2,2,1,...,1,2,2,2,2,2,2,2,2,1
3,5001,1,3,SIV_2022,2,761.19639279,3,2,2,1,...,2,1,2,2,2,2,2,2,2,2
4,5001,1,4,SIV_2022,1,761.19639279,3,3,2,1,...,1,1,1,2,2,2,2,2,2,3

In [49]:
sisben.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1621805 entries, 0 to 1621804
Data columns (total 33 columns):
 #   Column    Non-Null Count    Dtype
---  ------    --------------    -----
 0   cod_mpio  1621805 non-null  int64
 1   ZONA      1621805 non-null  int64
 2   llave     1621805 non-null  int64
 3   CORTE     1621805 non-null  object
 4   HOGAR     1621805 non-null  int64
 5   FEX       1621805 non-null  object
 6   HOG001    1621805 non-null  int64
 7   HOG002    1621805 non-null  int64
 8   HOG003    1621805 non-null  int64
 9   HOG004    1621805 non-null  int64
 10  HOG005    1621805 non-null  int64
 11  HOG006    1621805 non-null  int64
 12  HOG007    1621805 non-null  int64
 13  HOG008    1621805 non-null  int64
 14  HOG009    1621805 non-null  int64
 15  HOG010    1621805 non-null  int64
 16  HOG011    1621805 non-null  int64
 17  HOG012    1621805 non-null  int64
 18  HOG013    1621805 non-null  int64
 19  HOG014    1621805 non-null  int64
 20  HOG015    1621805 non-null  int64
 21  HOG016    1621805 non-null  int64
 22  HOG017    1621805 non-null  int64
 23  HOG018    1621805 non-null  int64
 24  HOG019    1621805 non-null  int64
 25  HOG020    1621805 non-null  int64
 26  HOG021    1621805 non-null  int64
 27  HOG022    1621805 non-null  int64
 28  HOG023    1621805 non-null  int64
 29  HOG024    1621805 non-null  int64
 30  HOG025    1621805 non-null  int64
 31  HOG026    1621805 non-null  int64
 32  HOG027    1621805 non-null  int64
dtypes: int64(31), object(2)
memory usage: 408.3+ MB

In [51]:
sisben.describe()

,cod_mpio,ZONA,llave,HOGAR,HOG001,HOG002,HOG003,HOG004,HOG005,HOG006,...,HOG018,HOG019,HOG020,HOG021,HOG022,HOG023,HOG024,HOG025,HOG026,HOG027
count,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06,...,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06,1.621805e+06
mean,3.888847e+04,1.543217e+00,7.825894e+02,1.148956e+00,3.107873e+00,1.911214e+00,1.430834e+00,2.128576e+00,2.032395e+00,2.138540e+00,...,1.634695e+00,1.859419e+00,1.958804e+00,1.843407e+00,1.956588e+00,1.992800e+00,1.991357e+00,1.884404e+00,1.946637e+00,2.752923e+00
std,2.549820e+04,4.981289e-01,5.585866e+02,4.810670e-01,1.230702e+00,1.121398e+00,7.919989e-01,1.227606e+00,2.171320e+00,2.210098e+00,...,4.815156e-01,3.475889e-01,1.987435e-01,3.634165e-01,2.037831e-01,8.454683e-02,9.256428e-02,3.197398e-01,2.247571e-01,1.599561e+00
min,5.001000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
25%,1.586100e+04,1.000000e+00,3.370000e+02,1.000000e+00,3.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00
50%,2.716000e+04,2.000000e+00,6.850000e+02,1.000000e+00,3.000000e+00,2.000000e+00,1.000000e+00,2.000000e+00,1.000000e+00,1.000000e+00,...,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00
75%,6.369000e+04,2.000000e+00,1.121000e+03,1.000000e+00,4.000000e+00,3.000000e+00,2.000000e+00,3.000000e+00,2.000000e+00,2.000000e+00,...,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,4.000000e+00
max,9.977300e+04,2.000000e+00,3.401000e+03,1.500000e+01,5.000000e+00,1.500000e+01,1.500000e+01,5.000000e+00,9.000000e+00,9.000000e+00,...,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.100000e+01

Este ejercicio es probabilistico, por lo que es preciso evaluar su inclusión dentro del modelo. Sin embargo, sería interesante ver su comportamiento a nivel municipal detallado, ya que se esperaria que en zonas donde haya una alta presencia de los distintos niveles de Sisben, se presente un mayor volumen de pagos, transferencias, etc.

In [52]:
sisben.to_csv("data/processed/pila1.csv")

Sisben población

In [53]:
sisben_pob=pd.read_csv("data/raw/SISBEN_POB/POBLACIÓN_SISBÉN_-_GÉNERO_Y_EDAD_20251018.csv")

In [54]:
sisben_pob.head()

                  FICHA  HOGAR  ZONA     BARRIO      VEREDA  GÉNERO  EDAD
0  68655000553600000000      1     1   VILLAPAZ  SIN VEREDA       1     5
1  68655000553600000000      1     1   VILLAPAZ  SIN VEREDA       3    23
2  68655000553600000000      1     1   VILLAPAZ  SIN VEREDA       3    30
3  68655000553600000000      1     1   VILLAPAZ  SIN VEREDA       1     1
4  68655001554200000000      1     1  COMUNEROS  SIN VEREDA       3    28

In [55]:
sisben_pob.describe()

              HOGAR          ZONA        GÉNERO          EDAD
count  30270.000000  30270.000000  30270.000000  30270.000000
mean       1.397390      1.584044      2.635811     30.734324
std        0.742796      0.856511      1.174705     20.466023
min        1.000000      1.000000      1.000000      0.000000
25%        1.000000      1.000000      2.000000     14.000000
50%        1.000000      1.000000      3.000000     28.000000
75%        2.000000      2.000000      3.000000     45.000000
max        5.000000      3.000000      9.000000    101.000000

Esta base es de orientación más poblacional, y puede resultar de utilidad para el análisis más poblacional de los municipios. Ahora bien, se percibe que la edad de las personas en el SISBEN es relativamente baja, sugiriendo que a medida que la persona tenga más edad pueda percibir más ingresos. Adicional, hay presencia de menores de edad en la base. Un elemento adicional, es que la información está a nivel de barrio y vereda, por lo que sería necesario identificar si a través del ID Ficha es posible imputar municipio.

In [56]:
sisben_pob.to_csv("data/processed/sisben_pob.csv")

# subsidiado

In [1]:
import pandas as pd

In [2]:
subsidiado=pd.read_csv("data/raw/afiliados_subsidiado/Población_Base_de_Datos_Única_de_Afiliados_BDUA_del_régimen_subsidiado_20251018.csv")

In [3]:
subsidiado.head()

,Genero,Grupo etario,Código de la entidad,Nombre de la entidad,Régimen al que pertenece,Tipo de afiliado,Estado del afiliado,Condición del beneficiario,Zona de Afiliación,Departamento,Municipio,Nivel del Sisbén,Grupo poblacional del afiliado,cantidad
0,Masculino,50 a 55,ESS207,ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SAL...,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Rural,CORDOBA,CHINU,2,POBLACIÓN CON SISBEN,6
1,Masculino,19 a 45,ESS207,ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SAL...,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana-Cabecera Municipal,SUCRE,MORROA,N,VÍCTIMAS DEL CONFLICTO ARMADO INTERNO,4
2,Femenino,1 a 5,ESS024,COOSALUD EPS S.A.,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana,MAGDALENA,SABANA DE SAN ANGEL,C,RECIÉN NACIDO Y MENOR DE EDAD DE PADRES NO AFI...,1
3,Masculino,45 a 50,ESS024,COOSALUD EPS S.A.,Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Urbana,MAGDALENA,REMOLINO,N,VÍCTIMAS DEL CONFLICTO ARMADO INTERNO,55
4,Femenino,< 1,EPSS41,NUEVA EPS S.A.,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana,META,VILLAVICENCIO,N,RECIÉN NACIDO Y MENOR DE EDAD DE PADRES NO AFI...,7

In [6]:
#limpiamos departamento y municipio para poder hacer el cruce
from unidecode import unidecode

subsidiado["Departamento"] = (
    subsidiado["Departamento"]
    .astype(str)                               # asegura que sean strings
    .str.strip()                               # quita espacios al inicio y final
    .apply(lambda x: unidecode(x))             # quita tildes y caracteres especiales
    .str.replace(r"\s+", "", regex=True)  # colapsa múltiples espacios en uno solo
)

In [7]:
subsidiado["Municipio"] = (
    subsidiado["Municipio"]
    .astype(str)                               # asegura que sean strings
    .str.strip()                               # quita espacios al inicio y final
    .apply(lambda x: unidecode(x))             # quita tildes y caracteres especiales
    .str.replace(r"\s+", "", regex=True)  # colapsa múltiples espacios en uno solo
)

In [8]:
subsidiado["key"]=subsidiado["Departamento"]+subsidiado["Municipio"]

In [5]:
#pegamos divipola
divipola=pd.read_excel("data/interim/DIVIPOLA_Municipios.xlsx")

In [9]:
divipola.head()

  doc_dep departamento  cod_muni   municipio
0      05    ANTIOQUIA    5001.0    MEDELLÍN
1      05    ANTIOQUIA    5002.0   ABEJORRAL
2      05    ANTIOQUIA    5004.0    ABRIAQUÍ
3      05    ANTIOQUIA    5021.0  ALEJANDRÍA
4      05    ANTIOQUIA    5030.0       AMAGÁ

In [10]:
divipola["departamento"] = (
    divipola["departamento"]
    .astype(str)                               # asegura que sean strings
    .str.strip()                               # quita espacios al inicio y final
    .apply(lambda x: unidecode(x))             # quita tildes y caracteres especiales
    .str.replace(r"\s+", "", regex=True)  # colapsa múltiples espacios en uno solo
)

In [11]:
divipola["municipio"] = (
    divipola["municipio"]
    .astype(str)                               # asegura que sean strings
    .str.strip()                               # quita espacios al inicio y final
    .apply(lambda x: unidecode(x))             # quita tildes y caracteres especiales
    .str.replace(r"\s+", "", regex=True)  # colapsa múltiples espacios en uno solo
)

In [12]:
divipola["key"]=divipola["departamento"]+divipola["municipio"]

In [13]:
subsidiado_final=pd.merge(subsidiado, divipola, how="left", on="key")

In [14]:
subsidiado_final.head()

,Genero,Grupo etario,Código de la entidad,Nombre de la entidad,Régimen al que pertenece,Tipo de afiliado,Estado del afiliado,Condición del beneficiario,Zona de Afiliación,Departamento,Municipio,Nivel del Sisbén,Grupo poblacional del afiliado,cantidad,key,doc_dep,departamento,cod_muni,municipio
0,Masculino,50 a 55,ESS207,ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SAL...,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Rural,CORDOBA,CHINU,2,POBLACIÓN CON SISBEN,6,CORDOBACHINU,23,CORDOBA,23182.0,CHINU
1,Masculino,19 a 45,ESS207,ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SAL...,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana-Cabecera Municipal,SUCRE,MORROA,N,VÍCTIMAS DEL CONFLICTO ARMADO INTERNO,4,SUCREMORROA,70,SUCRE,70473.0,MORROA
2,Femenino,1 a 5,ESS024,COOSALUD EPS S.A.,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana,MAGDALENA,SABANADESANANGEL,C,RECIÉN NACIDO Y MENOR DE EDAD DE PADRES NO AFI...,1,MAGDALENASABANADESANANGEL,NaN,NaN,NaN,NaN
3,Masculino,45 a 50,ESS024,COOSALUD EPS S.A.,Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Urbana,MAGDALENA,REMOLINO,N,VÍCTIMAS DEL CONFLICTO ARMADO INTERNO,55,MAGDALENAREMOLINO,47,MAGDALENA,47605.0,REMOLINO
4,Femenino,< 1,EPSS41,NUEVA EPS S.A.,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana,META,VILLAVICENCIO,N,RECIÉN NACIDO Y MENOR DE EDAD DE PADRES NO AFI...,7,METAVILLAVICENCIO,50,META,50001.0,VILLAVICENCIO

In [17]:
subsidiado_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1210054 entries, 0 to 1210053
Data columns (total 19 columns):
 #   Column                          Non-Null Count    Dtype
---  ------                          --------------    -----
 0   Genero                          1210054 non-null  object
 1   Grupo etario                    1210054 non-null  object
 2   Código de la entidad            1210054 non-null  object
 3   Nombre de la entidad            1210054 non-null  object
 4   Régimen al que pertenece        1210054 non-null  object
 5   Tipo de afiliado                1210054 non-null  object
 6   Estado del afiliado             1210054 non-null  object
 7   Condición del beneficiario      1210054 non-null  object
 8   Zona de Afiliación              1210054 non-null  object
 9   Departamento                    1210054 non-null  object
 10  Municipio                       1210054 non-null  object
 11  Nivel del Sisbén                1208315 non-null  object
 12  Grupo poblacional del afiliado  1192339 non-null  object
 13  cantidad                        1210054 non-null  int64
 14  key                             1210054 non-null  object
 15  doc_dep                         1053301 non-null  object
 16  departamento                    1053301 non-null  object
 17  cod_muni                        1053301 non-null  float64
 18  municipio                       1053301 non-null  object
dtypes: float64(1), int64(1), object(17)
memory usage: 175.4+ MB

In [16]:
#verificamos NA
print(subsidiado_final["cod_muni"].isna().sum())

156753

In [20]:
subsidiado_final_na=subsidiado_final[subsidiado_final["cod_muni"].isna()]

In [21]:
subsidiado_final_na.head()

,Genero,Grupo etario,Código de la entidad,Nombre de la entidad,Régimen al que pertenece,Tipo de afiliado,Estado del afiliado,Condición del beneficiario,Zona de Afiliación,Departamento,Municipio,Nivel del Sisbén,Grupo poblacional del afiliado,cantidad,key,doc_dep,departamento,cod_muni,municipio
2,Femenino,1 a 5,ESS024,COOSALUD EPS S.A.,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana,MAGDALENA,SABANADESANANGEL,C,RECIÉN NACIDO Y MENOR DE EDAD DE PADRES NO AFI...,1,MAGDALENASABANADESANANGEL,NaN,NaN,NaN,NaN
5,Femenino,19 a 45,EPSS02,SALUD TOTAL ENTIDAD PROMOTORA DE SALUD DEL REG...,Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Urbana,VALLE,ELCERRITO,1,POBLACIÓN CON SISBEN,45,VALLEELCERRITO,NaN,NaN,NaN,NaN
23,Femenino,1 a 5,ESS024,COOSALUD EPS S.A.,Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Rural,VALLE,PALMIRA,N,RECIÉN NACIDO Y MENOR DE EDAD DE PADRES NO AFI...,4,VALLEPALMIRA,NaN,NaN,NaN,NaN
36,Masculino,19 a 45,EPSS42,COOSALUD EPS S.A. -CM,Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Urbana,MAGDALENA,SABANADESANANGEL,N,VÍCTIMAS DEL CONFLICTO ARMADO INTERNO,1,MAGDALENASABANADESANANGEL,NaN,NaN,NaN,NaN
37,Masculino,1 a 5,EPSS41,NUEVA EPS S.A.,Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Rural,CHOCO,CANTONDESANPABLO,N,RECIÉN NACIDO Y MENOR DE EDAD DE PADRES NO AFI...,4,CHOCOCANTONDESANPABLO,NaN,NaN,NaN,NaN

La base de subsidiados tiene mal escritos algunos municipios del país, es necesario hacer una corrección detallada de los municipios que hay que ajustar para evitar inconvenientes en los cruces de información que se realicen

In [22]:
subsidiado_final.describe()

           cantidad      cod_muni
count  1.210054e+06  1.053301e+06
mean   2.207340e+01  3.743812e+04
std    1.891845e+02  2.494420e+04
min    1.000000e+00  5.001000e+03
25%    1.000000e+00  1.586100e+04
50%    2.000000e+00  2.581700e+04
75%    9.000000e+00  5.466000e+04
max    6.461500e+04  9.977300e+04

la única información númerica que se puede hacer descriptivas es cantidad, que tiene un muy alta desviación estándar, lo cual sugiere que pueden haber dinámicas urbanas afectando la variable, donde como es de esperarse, municipios de mayor categoría pueden arrastrar la distribución de la variable.

In [23]:
subsidiado_final.to_csv("data/processed/subsidiado.csv")

# contributivo

In [26]:
contributivo=pd.read_csv("data/raw/afiliados_contributivo/Población_Base_de_Datos_Única_de_Afiliados_BDUA_del_régimen_contributivo_20251018.csv")

In [27]:
contributivo.head()

,Género,Grupo etario,Código de la entidad,Nombre de la entidad,Régimen,Tipo de afiliado,Estado del afiliado,Condición del beneficiario,Zona de Afiliación,Departamento,Municipio,tps_nvl_ssb_id,Nivel del Sisbén,Cantidad de registros
0,Masculino,19 a 45,ESS207,ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SAL...,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana-Cabecera Municipal,SUCRE,MORROA,N,VÍCTIMAS DEL CONFLICTO ARMADO INTERNO,4
1,Femenino,1 a 5,ESS024,COOSALUD EPS S.A.,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana,MAGDALENA,SABANA DE SAN ANGEL,C,RECIÉN NACIDO Y MENOR DE EDAD DE PADRES NO AFI...,1
2,Masculino,45 a 50,ESS024,COOSALUD EPS S.A.,Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Urbana,MAGDALENA,REMOLINO,N,VÍCTIMAS DEL CONFLICTO ARMADO INTERNO,55
3,Femenino,< 1,EPSS41,NUEVA EPS S.A.,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana,META,VILLAVICENCIO,N,RECIÉN NACIDO Y MENOR DE EDAD DE PADRES NO AFI...,7
4,Femenino,60 a 65,EPSS40,"ALIANZA MEDELLIN ANTIOQUIA EPS S.A.S. ""SAVIA S...",Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Urbana-Cabecera Municipal,ANTIOQUIA,BARBOSA,N,HABITANTE DE LA CALLE,1

al igual que la base de subsidiado, se cuenta con una estructura similar, por lo que se pegará divipola para los municipios donde es posible realizarlo

In [28]:
contributivo["Departamento"] = (
    contributivo["Departamento"]
    .astype(str)                               # asegura que sean strings
    .str.strip()                               # quita espacios al inicio y final
    .apply(lambda x: unidecode(x))             # quita tildes y caracteres especiales
    .str.replace(r"\s+", "", regex=True)  # colapsa múltiples espacios en uno solo
)

In [29]:
contributivo["Municipio"] = (
    contributivo["Municipio"]
    .astype(str)                               # asegura que sean strings
    .str.strip()                               # quita espacios al inicio y final
    .apply(lambda x: unidecode(x))             # quita tildes y caracteres especiales
    .str.replace(r"\s+", "", regex=True)  # colapsa múltiples espacios en uno solo
)

In [30]:
contributivo["key"]=contributivo["Departamento"]+contributivo["Municipio"]

hacemmos el merge con divipola

In [31]:
contributivo_final=pd.merge(contributivo, divipola, how="left", on="key")

In [33]:
contributivo_final.head()

,Género,Grupo etario,Código de la entidad,Nombre de la entidad,Régimen,Tipo de afiliado,Estado del afiliado,Condición del beneficiario,Zona de Afiliación,Departamento,Municipio,tps_nvl_ssb_id,Nivel del Sisbén,Cantidad de registros,key,doc_dep,departamento,cod_muni,municipio
0,Masculino,19 a 45,ESS207,ASOCIACION MUTUAL SER EMPRESA SOLIDARIA DE SAL...,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana-Cabecera Municipal,SUCRE,MORROA,N,VÍCTIMAS DEL CONFLICTO ARMADO INTERNO,4,SUCREMORROA,70,SUCRE,70473.0,MORROA
1,Femenino,1 a 5,ESS024,COOSALUD EPS S.A.,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana,MAGDALENA,SABANADESANANGEL,C,RECIÉN NACIDO Y MENOR DE EDAD DE PADRES NO AFI...,1,MAGDALENASABANADESANANGEL,NaN,NaN,NaN,NaN
2,Masculino,45 a 50,ESS024,COOSALUD EPS S.A.,Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Urbana,MAGDALENA,REMOLINO,N,VÍCTIMAS DEL CONFLICTO ARMADO INTERNO,55,MAGDALENAREMOLINO,47,MAGDALENA,47605.0,REMOLINO
3,Femenino,< 1,EPSS41,NUEVA EPS S.A.,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana,META,VILLAVICENCIO,N,RECIÉN NACIDO Y MENOR DE EDAD DE PADRES NO AFI...,7,METAVILLAVICENCIO,50,META,50001.0,VILLAVICENCIO
4,Femenino,60 a 65,EPSS40,"ALIANZA MEDELLIN ANTIOQUIA EPS S.A.S. ""SAVIA S...",Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Urbana-Cabecera Municipal,ANTIOQUIA,BARBOSA,N,HABITANTE DE LA CALLE,1,ANTIOQUIABARBOSA,05,ANTIOQUIA,5079.0,BARBOSA

al igual que para la base de subsidiado, hay NAs por la mala imputación de municipios que hay que resolver

In [34]:
contributivo_final_na=contributivo_final[contributivo_final["cod_muni"].isna()]

In [35]:
contributivo_final_na.head()

,Género,Grupo etario,Código de la entidad,Nombre de la entidad,Régimen,Tipo de afiliado,Estado del afiliado,Condición del beneficiario,Zona de Afiliación,Departamento,Municipio,tps_nvl_ssb_id,Nivel del Sisbén,Cantidad de registros,key,doc_dep,departamento,cod_muni,municipio
1,Femenino,1 a 5,ESS024,COOSALUD EPS S.A.,Subsidiado,BENEFICIARIO,Activo,NO APLICA,Urbana,MAGDALENA,SABANADESANANGEL,C,RECIÉN NACIDO Y MENOR DE EDAD DE PADRES NO AFI...,1,MAGDALENASABANADESANANGEL,NaN,NaN,NaN,NaN
5,Femenino,19 a 45,EPSS02,SALUD TOTAL ENTIDAD PROMOTORA DE SALUD DEL REG...,Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Urbana,VALLE,ELCERRITO,1,POBLACIÓN CON SISBEN,45,VALLEELCERRITO,NaN,NaN,NaN,NaN
19,Femenino,45 a 50,EPSS17,EPS FAMISANAR S.A.S. -CM,Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Urbana-Cabecera Municipal,CUNDINAMARCA,ELPENOL,1,POBLACIÓN CON SISBEN,3,CUNDINAMARCAELPENOL,NaN,NaN,NaN,NaN
31,Femenino,1 a 5,ESS024,COOSALUD EPS S.A.,Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Rural,VALLE,PALMIRA,N,RECIÉN NACIDO Y MENOR DE EDAD DE PADRES NO AFI...,4,VALLEPALMIRA,NaN,NaN,NaN,NaN
45,Masculino,19 a 45,EPSS42,COOSALUD EPS S.A. -CM,Subsidiado,CABEZA DE FAMILIA,Activo,NO APLICA,Urbana,MAGDALENA,SABANADESANANGEL,N,VÍCTIMAS DEL CONFLICTO ARMADO INTERNO,1,MAGDALENASABANADESANANGEL,NaN,NaN,NaN,NaN

In [36]:
#guardamos csv
contributivo_final.to_csv("data/processed/contributivo.csv")

# RIPS

In [39]:
rips=pd.read_csv("data/raw/rips/Registros_Individuales_de_Prestación_de_Servicios_de_Salud_–_RIPS_20251018.csv", encoding="utf-8")

In [40]:
rips.head()

,Departamento,Municipio,Año,TipoAtencion,Diagnostico,NumeroAtenciones
0,05 - Antioquia,05212 - Copacabana,2012,CONSULTAS,F431 - TRASTORNO DE ESTRÃ‰S POSTRAUMATICO,2
1,05 - Antioquia,05576 - Pueblorrico,2011,CONSULTAS,"C779 - TUMOR MALIGNO DEL GANGLIO LINFATICO, SI...",1
2,05 - Antioquia,05086 - Belmira,2014,PROCEDIMIENTOS DE SALUD,Z340 - SUPERVISION DE PRIMER EMBARAZO NORMAL,48
3,05 - Antioquia,05490 - NecoclÃ­,2015,CONSULTAS,M545 - LUMBAGO NO ESPECIFICADO,961
4,05 - Antioquia,05212 - Copacabana,2012,CONSULTAS,F510 - INSOMNIO NO ORGANICO,32

## separamos columnas de departamento y municipio

In [41]:
# Separar Departamento
rips[['CodDepartamento', 'NomDepartamento']] = (
    rips['Departamento'].str.split(' - ', n=1, expand=True)
)

# Separar Municipio
rips[['CodMunicipio', 'NomMunicipio']] = (
    rips['Municipio'].str.split(' - ', n=1, expand=True)
)

In [42]:
rips.head()

,Departamento,Municipio,Año,TipoAtencion,Diagnostico,NumeroAtenciones,CodDepartamento,NomDepartamento,CodMunicipio,NomMunicipio
0,05 - Antioquia,05212 - Copacabana,2012,CONSULTAS,F431 - TRASTORNO DE ESTRÃ‰S POSTRAUMATICO,2,05,Antioquia,05212,Copacabana
1,05 - Antioquia,05576 - Pueblorrico,2011,CONSULTAS,"C779 - TUMOR MALIGNO DEL GANGLIO LINFATICO, SI...",1,05,Antioquia,05576,Pueblorrico
2,05 - Antioquia,05086 - Belmira,2014,PROCEDIMIENTOS DE SALUD,Z340 - SUPERVISION DE PRIMER EMBARAZO NORMAL,48,05,Antioquia,05086,Belmira
3,05 - Antioquia,05490 - NecoclÃ­,2015,CONSULTAS,M545 - LUMBAGO NO ESPECIFICADO,961,05,Antioquia,05490,NecoclÃ­
4,05 - Antioquia,05212 - Copacabana,2012,CONSULTAS,F510 - INSOMNIO NO ORGANICO,32,05,Antioquia,05212,Copacabana

In [43]:
rips.describe()

                Año  NumeroAtenciones
count  3.800000e+07      3.800000e+07
mean   2.015817e+03      1.008742e+02
std    3.634781e+00      1.086882e+04
min    2.009000e+03      1.000000e+00
25%    2.013000e+03      1.000000e+00
50%    2.016000e+03      3.000000e+00
75%    2.019000e+03      1.000000e+01
max    2.021000e+03      1.861965e+07

se presenta el mismo problema que en las bases anterirores, y es que la desviación estándar da ciertas nociones de concentración en regiones densamente pobladas

In [44]:
rips.to_csv("data/processed/rips.csv")